#!/bin/sh

set -e

PREREQ="cryptroot"

prereqs()
{
        echo "$PREREQ"
}

case $1 in
prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

# Install binaries into initramfs.
# Note we don't need to install kxc-cryptsetup, as the cryptroot hook will do
# it for us if it sees it being used as a keyscript.
copy_exec /usr/bin/kxc /bin

# Install the configuration into initramfs (if it exists).
if [ -d /etc/kxc/ ]; then
	cp -a /etc/kxc/ ${DESTDIR}/etc
fi
